const priceListsData = [
  {
    id: 'pl-1',
    name: 'Retail Price List',
    applicableCustomers: 'all',
    applicableItems: 'all',
    pricingMethod: 'fixed',
    rules: [],
    validity: { from: '2025-01-01', to: '2025-12-31' },
    status: 'Active',
    selectedCustomerIds: [],
    selectedItemIds: [],
    customerGroupId: '',
    itemGroupId: '',
    fixedValue: null,
    discountPercent: null,
    markupPercent: null,
  },
  {
    id: 'pl-2',
    name: 'Wholesale Discount 15%',
    applicableCustomers: 'selected',
    applicableItems: 'all',
    pricingMethod: 'discount_mrp',
    rules: [
      { itemId: 'itm-1', variantId: 'var-1', basePrice: 2199, discountPercent: 15, finalPrice: 1869.15 },
      { itemId: 'itm-2', variantId: 'var-4', basePrice: 699, discountPercent: 15, finalPrice: 594.15 },
    ],
    validity: { from: '2025-02-01', to: '2025-12-31' },
    status: 'Active',
    selectedCustomerIds: ['cus-1', 'cus-2'],
    selectedItemIds: [],
    customerGroupId: '',
    itemGroupId: '',
    fixedValue: null,
    discountPercent: 15,
    markupPercent: null,
  },
  {
    id: 'pl-3',
    name: 'VIP Markup 25%',
    applicableCustomers: 'group',
    applicableItems: 'group',
    pricingMethod: 'markup_cost',
    rules: [],
    validity: { from: '2025-01-15', to: '2025-06-30' },
    status: 'Inactive',
    selectedCustomerIds: [],
    selectedItemIds: [],
    customerGroupId: '65f1a2c3b4d5e6f7a8b9c101',
    itemGroupId: '65f1a2c3b4d5e6f7a8b9c102',
    fixedValue: null,
    discountPercent: null,
    markupPercent: 25,
  },
];

const schemesData = [
  {
    id: 'sch-1',
    name: 'Festival Sale 20%',
    type: 'percentage_discount',
    applicability: { type: 'item', ids: ['itm-1', 'itm-2'] },
    conditions: { minQuantity: 2, minValue: 1000 },
    benefit: { discountPercent: 20, flatAmount: null, buyQty: null, getQty: null },
    giftItemId: null,
    giftQuantity: null,
    validity: { from: '2025-02-01', to: '2025-02-28' },
    status: 'Active',
  },
  {
    id: 'sch-2',
    name: 'Flat ₹200 Off',
    type: 'flat_discount',
    applicability: { type: 'brand', ids: ['br-1'] },
    conditions: { minQuantity: 1, minValue: 1500 },
    benefit: { discountPercent: null, flatAmount: 200, buyQty: null, getQty: null },
    giftItemId: null,
    giftQuantity: null,
    validity: { from: '2025-01-01', to: '2025-03-31' },
    status: 'Active',
  },
  {
    id: 'sch-3',
    name: 'Buy 2 Get 1 Free',
    type: 'buy_x_get_y',
    applicability: { type: 'itemGroup', ids: ['65f1a2c3b4d5e6f7a8b9c102'] },
    conditions: { minQuantity: 2, minValue: 0 },
    benefit: { discountPercent: null, flatAmount: null, buyQty: 2, getQty: 1 },
    giftItemId: null,
    giftQuantity: null,
    validity: { from: '2025-02-15', to: '2025-03-15' },
    status: 'Active',
  },
  {
    id: 'sch-4',
    name: 'Free Gift - Cotton Tee',
    type: 'free_gift',
    applicability: { type: 'item', ids: ['itm-1'] },
    conditions: { minQuantity: 1, minValue: 2999 },
    benefit: { discountPercent: null, flatAmount: null, buyQty: null, getQty: null },
    giftItemId: 'itm-2',
    giftQuantity: 1,
    validity: { from: '2025-02-01', to: '2025-02-28' },
    status: 'Active',
  },
];

const couponsData = [
  {
    id: 'cpn-1',
    code: 'SAVE20',
    discountType: 'percentage',
    value: 20,
    minAmount: 2000,
    usageLimit: 100,
    usageCount: 34,
    expiry: '2025-12-31',
    status: 'Active',
  },
  {
    id: 'cpn-2',
    code: 'FLAT100',
    discountType: 'amount',
    value: 100,
    minAmount: 500,
    usageLimit: 500,
    usageCount: 156,
    expiry: '2025-06-30',
    status: 'Active',
  },
  {
    id: 'cpn-3',
    code: 'WELCOME50',
    discountType: 'percentage',
    value: 50,
    minAmount: 1000,
    usageLimit: 10,
    usageCount: 10,
    expiry: '2025-01-31',
    status: 'Expired',
  },
];

export { priceListsData, schemesData, couponsData };
export default { priceListsData, schemesData, couponsData };
