const itemsExportColumns = [
  { key: 'item_code', label: 'Item Code', order: 1 },
  { key: 'item_name', label: 'Item Name', order: 2 },
  { key: 'brand', label: 'Brand', order: 3 },
  { key: 'hsn_code', label: 'HSN Code', order: 4 },
  { key: 'gst_rate', label: 'GST Rate', order: 5 },
  { key: 'color', label: 'Color', order: 6 },
  { key: 'fabric', label: 'Fabric', order: 7 },
  { key: 'type', label: 'Type', order: 8 },
  { key: 'pattern', label: 'Pattern', order: 9 },
  { key: 'fit', label: 'Fit', order: 10 },
  { key: 'sleeve_type', label: 'Sleeve Type', order: 11 },
  { key: 'neck_type', label: 'Neck Type', order: 12 },
  { key: 'gender', label: 'Gender', order: 13 },
  { key: 'season', label: 'Season', order: 14 },
  { key: 'occasion', label: 'Occasion', order: 15 },
  { key: 'material_composition', label: 'Material Composition', order: 16 },
  { key: 'main_group', label: 'Main Group', order: 17 },
  { key: 'sub_group', label: 'Sub Group', order: 18 },
  { key: 'category_path', label: 'Category Path', order: 19 },
  { key: 'size', label: 'Size', order: 20 },
  { key: 'cost_price', label: 'Cost Price', order: 21 },
  { key: 'sale_price', label: 'Sale Price', order: 22 },
  { key: 'mrp', label: 'MRP', order: 23 },
  { key: 'sku', label: 'SKU', order: 24 },
  { key: 'default_warehouse', label: 'Default Warehouse', order: 25 },
  { key: 'reorder_level', label: 'Reorder Level', order: 26 },
  { key: 'reorder_qty', label: 'Reorder Qty', order: 27 },
  { key: 'opening_stock', label: 'Opening Stock', order: 28 },
  { key: 'opening_stock_rate', label: 'Opening Stock Rate', order: 29 },
  { key: 'status', label: 'Status', order: 30 },
];

export default itemsExportColumns;

