const itemsData = [
  {
    id: 'itm-1',
    name: 'Classic Denim Jacket',
    code: 'STY-DNM-JKT',
    brand: 'North Trail Denim',
    category: 'Denim Jackets',
    description: 'Regular fit denim jacket with contrast stitching.',
    attributes: {
      gender: 'Men',
      season: 'Winter',
      fabric: 'Denim',
      fabricType: 'Cotton Blend',
    },
    image: null,
    status: 'Active',
    variants: [
      {
        id: 'var-1',
        size: 'M',
        color: 'Blue',
        sku: 'STY-DNM-JKT-M-BLUE',
        costPrice: 1250,
        sellingPrice: 1899,
        mrp: 2199,
        stock: 42,
        status: 'Active',
      },
      {
        id: 'var-2',
        size: 'L',
        color: 'Blue',
        sku: 'STY-DNM-JKT-L-BLUE',
        costPrice: 1280,
        sellingPrice: 1949,
        mrp: 2299,
        stock: 36,
        status: 'Active',
      },
      {
        id: 'var-3',
        size: 'XL',
        color: 'Black',
        sku: 'STY-DNM-JKT-XL-BLACK',
        costPrice: 1310,
        sellingPrice: 1999,
        mrp: 2399,
        stock: 18,
        status: 'Inactive',
      },
    ],
  },
  {
    id: 'itm-2',
    name: 'Essential Cotton Tee',
    code: 'STY-CTN-TEE',
    brand: 'Zeto Originals',
    category: 'Menswear',
    description: 'Soft touch crew neck cotton t-shirt.',
    attributes: {
      gender: 'Unisex',
      season: 'All Season',
      fabric: 'Cotton',
      fabricType: 'Combed Cotton',
    },
    image: null,
    status: 'Active',
    variants: [
      {
        id: 'var-4',
        size: 'S',
        color: 'White',
        sku: 'STY-CTN-TEE-S-WHITE',
        costPrice: 250,
        sellingPrice: 499,
        mrp: 699,
        stock: 120,
        status: 'Active',
      },
      {
        id: 'var-5',
        size: 'M',
        color: 'Black',
        sku: 'STY-CTN-TEE-M-BLACK',
        costPrice: 255,
        sellingPrice: 549,
        mrp: 749,
        stock: 98,
        status: 'Active',
      },
    ],
  },
];

export default itemsData;
