import React, { useState, useMemo } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Box,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Alert,
  CircularProgress,
  Stack,
  IconButton,
  LinearProgress,
  TablePagination,
  FormControlLabel,
  Checkbox,
  Backdrop
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import * as XLSX from 'xlsx';
import api from '../../../services/api';

const BulkItemUploadDialog = ({ open, onClose, onUploadSuccess }) => {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [generateNewBarcodes, setGenerateNewBarcodes] = useState(false);
  
  // Pagination state
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(10);

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setLoading(true);
    setError('');
    
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const bstr = event.target.result;
        const wb = XLSX.read(bstr, { type: 'binary' });
        const wsname = wb.SheetNames[0];
        const ws = wb.Sheets[wsname];
        const json = XLSX.utils.sheet_to_json(ws);
        
        if (json.length === 0) {
          setError('The Excel file is empty.');
          setLoading(false);
          return;
        }

        const standardizedData = json.map(row => {
          const newRow = {};
          Object.keys(row).forEach(key => {
            // Remove special characters, spaces to underscores, and lowercase
            const standardizedKey = key.toString()
              .toLowerCase()
              .trim()
              .replace(/[^a-z0-9]/g, '_')
              .replace(/_+/g, '_');
            newRow[standardizedKey] = row[key];
          });
          return newRow;
        });

        setData(standardizedData);
      } catch (err) {
        setError('Failed to parse Excel file. Please ensure it is a valid .xlsx or .xls file.');
      } finally {
        setLoading(false);
      }
    };
    reader.readAsBinaryString(file);
  };

  const groupedItems = useMemo(() => {
    const items = {};
    data.forEach(row => {
      // Very flexible code detection based on user's specific Excel headers
      // MNO or ITEM CODE
      const code = row.item_code || row.mno || row.style_code || row.code || row.sku || 
                   row.style_no || row.article_no || row.barcode || row.barcode_no;

      if (!code) return;

      const codeStr = String(code).trim().toUpperCase();

      if (!items[codeStr]) {
        items[codeStr] = {
          itemCode: codeStr,
          itemName: row.item_name || row.name || row.product_name || row.item_description || row.description || codeStr,
          brandName: row.brand || row.brand_name || row.mfr_name,
          sectionName: row.group_dep1 || row.section || row.department || row.dept,
          categoryName: row.category || row.category_name || row.group,
          subCategoryName: row.group_dep2 || row.sub_category || row.sub_category_name || row.sub_group,
          styleName: row.type || row.style || row.style_type || row.style_name,
          hsnCode: row.hsn_code || row.hsn || row.hsn_no,
          uom: row.uom || row.unit || 'PCS',
          fabric: row.fabric || row.material,
          composition: row.fabric_type || row.composition || row.fabric_details,
          color: row.shade || row.color || row.shade_no || 'N/A',
          pattern: row.pattern || row.design,
          fit: row.fit,
          gender: row.gender,
          description: row.item_description || row.description || row.remarks,
          packingType: row.inner || row.inner_box || row.outer_box || row.packing_type || row.packing,
          vendorId: row.vendor || row.vendor_name || row.supplier,
          type: 'GARMENT', // Force valid enum value
          sizes: []
        };
      }

      // Add variant
      // Smart Barcode: Use from Excel if exists, otherwise null (to be generated by backend)
      const excelBarcode = row.sku || row.barcode || row.barcode_code || row.barcode_no || row.variant_sku || row.upc;
      const finalBarcode = excelBarcode && String(excelBarcode).trim() !== '' ? String(excelBarcode).trim() : null;

      // Aggressive Color Detection
      const rowColor = (row.shade || row.color || row.shade_name || row.color_name || row.shade_no || '').toString().trim();

      items[codeStr].sizes.push({
        size: row.size || row.variant_size || 'Standard',
        color: rowColor || items[codeStr].color || 'N/A',
        sku: finalBarcode,
        barcode: finalBarcode,
        mrp: Number(row.mrp || row.price || row.rate || 0),
        stock: Number(row.stock || row.opening_stock || row.qty || row.quantity || 0),
        status: 'Active'
      });

      // Update parent color if it was N/A
      if (items[codeStr].color === 'N/A' && rowColor) {
        items[codeStr].color = rowColor;
      }
    });
    return Object.values(items);
  }, [data]);

  const handleSave = async () => {
    setUploading(true);
    setProgress(0);
    setError('');
    
    const total = groupedItems.length;
    const batchSize = 1000; // Increased from 20 to 1000 for high-speed upload
    const totalBatches = Math.ceil(total / batchSize);
    let successCount = 0;
    let errorCount = 0;

    try {
      for (let i = 0; i < totalBatches; i++) {
        const start = i * batchSize;
        const end = Math.min(start + batchSize, total);
        const batch = groupedItems.slice(start, end);

        const response = await api.post('/items/bulk', batch);
        
        // Defensive check for response data
        const resData = response?.data?.data || response?.data || {};
        const batchSuccess = resData.success?.length || 0;
        const batchErrors = (resData.errors?.length || resData.failed?.length || 0);
        
        successCount += batchSuccess;
        errorCount += batchErrors;

        setProgress(Math.round(((i + 1) / totalBatches) * 100));
      }

      setSuccess(`Upload complete! Successfully processed ${successCount} items. ${errorCount > 0 ? `${errorCount} items had issues.` : ''}`);
      if (onUploadSuccess) onUploadSuccess();
    } catch (err) {
      console.error('Detailed Upload Error:', err);
      const serverMsg = err.response?.data?.message || err.message;
      setError(`Upload failed: ${serverMsg}. Please try refreshing the page or using a smaller file.`);
    } finally {
      setUploading(false);
    }
  };

  const handleChangePage = (event, newPage) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  const handleClose = () => {
    setData([]);
    setError('');
    setSuccess('');
    setProgress(0);
    setPage(0);
    onClose();
  };

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="lg" fullWidth>
      <DialogTitle>
        <Stack direction="row" justifyContent="space-between" alignItems="center">
          <Typography variant="h6" sx={{ fontWeight: 800 }}>Bulk Excel Upload - Items</Typography>
          <IconButton onClick={handleClose} size="small"><CloseIcon /></IconButton>
        </Stack>
      </DialogTitle>
      <DialogContent dividers>
        <Box sx={{ mb: 3 }}>
          <Alert severity="info" sx={{ mb: 2 }}>
            Upload an Excel file with columns like: <b>Item Code, Item Name, Brand, Section, Category, Sub Category, HSN Code, Size, MRP, Stock, SKU/Barcode</b>.
            Multiple rows with the same Item Code will be grouped as variants.
          </Alert>

          <Button
            variant="outlined"
            component="label"
            startIcon={<CloudUploadIcon />}
            disabled={loading || uploading}
            fullWidth
            sx={{ py: 2, borderStyle: 'dashed', borderWidth: 2 }}
          >
            {data.length > 0 ? 'Change File' : 'Select Excel File'}
            <input type="file" hidden accept=".xlsx, .xls" onChange={handleFileChange} />
          </Button>
        </Box>

        <Backdrop
          sx={{ color: '#fff', zIndex: (theme) => theme.zIndex.drawer + 1000, flexDirection: 'column', gap: 2 }}
          open={loading || uploading}
        >
          <CircularProgress color="inherit" />
          <Typography variant="h6">
            {uploading ? `Saving Data... (${progress}%)` : 'Processing Excel File...'}
          </Typography>
          {uploading && (
            <Box sx={{ width: '300px' }}>
              <LinearProgress variant="determinate" value={progress} color="secondary" />
            </Box>
          )}
        </Backdrop>

        {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
        {success && <Alert severity="success" sx={{ mb: 2 }}>{success}</Alert>}

        {data.length > 0 && !loading && (
          <Box>
            <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 700 }}>Preview ({groupedItems.length} unique items identified)</Typography>
            <TableContainer component={Paper} variant="outlined" sx={{ maxHeight: 600 }}>
              <Table size="small" stickyHeader sx={{ minWidth: 2000 }}>
                <TableHead>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc', position: 'sticky', left: 0, zIndex: 10 }}>Code</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc', position: 'sticky', left: 100, zIndex: 10 }}>Name</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc' }}>Brand</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc' }}>Category</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc' }}>Sub Category</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc' }}>Color</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc' }}>Fabric</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc' }}>Composition</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc' }}>Vendor</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc' }}>Packing</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc' }}>HSN</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc' }}>Description</TableCell>
                    <TableCell sx={{ fontWeight: 700, bgcolor: '#f8fafc', minWidth: 350 }}>Variants (Size | Barcode | MRP | Stock)</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {groupedItems.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage).map((item, idx) => (
                    <TableRow key={idx} hover>
                      <TableCell sx={{ fontWeight: 700, color: '#6366f1', verticalAlign: 'top', position: 'sticky', left: 0, bgcolor: 'white', zIndex: 5 }}>{item.itemCode}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top', position: 'sticky', left: 100, bgcolor: 'white', zIndex: 5 }}>{item.itemName}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top' }}>{item.brandName || '--'}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top' }}>{item.categoryName || '--'}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top' }}>{item.subCategoryName || '--'}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top' }}>{item.color || '--'}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top' }}>{item.fabric || '--'}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top' }}>{item.composition || '--'}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top' }}>{item.vendorId || '--'}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top' }}>{item.packingType || '--'}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top' }}>{item.hsnCode || '--'}</TableCell>
                      <TableCell sx={{ verticalAlign: 'top' }}>{item.description || '--'}</TableCell>
                      <TableCell>
                        <Stack spacing={0.5}>
                          {item.sizes.map((s, sidx) => (
                            <Box key={sidx} sx={{ 
                              display: 'flex', 
                              alignItems: 'center',
                              gap: 2,
                              p: 0.5, 
                              borderBottom: sidx < item.sizes.length - 1 ? '1px dashed #e2e8f0' : 'none',
                              fontSize: '0.75rem'
                            }}>
                              <Typography variant="caption" sx={{ fontWeight: 800, minWidth: 40 }}>{s.size}</Typography>
                              <Typography variant="caption" sx={{ 
                                color: generateNewBarcodes ? '#d97706' : (s.sku ? '#059669' : '#d97706'),
                                fontWeight: 700,
                                flexGrow: 1
                              }}>
                                {generateNewBarcodes ? 'WILL GENERATE' : (s.sku || 'AUTO-GEN')}
                              </Typography>
                              <Typography variant="caption" sx={{ fontWeight: 600, color: '#4f46e5' }}>
                                ₹{s.mrp}
                              </Typography>
                              <Typography variant="caption" sx={{ fontWeight: 600, color: '#64748b' }}>
                                S: {s.stock}
                              </Typography>
                            </Box>
                          ))}
                        </Stack>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
            <TablePagination
              rowsPerPageOptions={[10, 25, 50, 100]}
              component="div"
              count={groupedItems.length}
              rowsPerPage={rowsPerPage}
              page={page}
              onPageChange={handleChangePage}
              onRowsPerPageChange={handleChangeRowsPerPage}
            />
          </Box>
        )}
      </DialogContent>
      <DialogActions sx={{ p: 2, bgcolor: '#f8fafc' }}>
        <Button onClick={handleClose} disabled={uploading}>Cancel</Button>
        <Button
          variant="contained"
          onClick={handleSave}
          disabled={groupedItems.length === 0 || uploading}
          startIcon={uploading ? <CircularProgress size={20} /> : null}
          sx={{ fontWeight: 700, px: 4 }}
        >
          {uploading ? 'Uploading...' : 'Save All Items'}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default BulkItemUploadDialog;
