const authRoutes = require('./modules/auth/auth.routes');
const groupRoutes = require('./modules/groups/group.routes');
const itemRoutes = require('./modules/items/item.routes');
const importRoutes = require('./modules/import/import.routes');
const setupRoutes = require('./modules/setup/setup.routes');
const inventoryRoutes = require('./modules/inventory/inventory.routes');
const { requireAdmin } = require('./middlewares/role.middleware');
const { protect } = require('./middlewares/auth.middleware');
const { activityLogger } = require('./middlewares/logger.middleware');

const registerRoutes = (app) => {
    app.use(activityLogger('ERP_SYSTEM'));
    app.use('/api/auth', authRoutes);
    app.use('/api/media', require('./modules/media/media.routes'));
    app.use('/api/groups', protect, groupRoutes);
    app.use('/api/accounts/vouchers', protect, require('./modules/accountingVouchers/accountingVoucher.routes'));
    app.use('/api/accounts', protect, require('./modules/accounts/account.routes'));
    app.use('/api/import', protect, requireAdmin, importRoutes);
    app.use('/api/setup', protect, setupRoutes);
    app.use('/api/sizes', protect, require('./modules/sizes/size.routes.js'));
    app.use('/api/items', itemRoutes);
    app.use('/api/inventory', inventoryRoutes);
    app.use('/api/store-inventory', protect, require('./modules/storeInventory/storeInventory.routes'));
    app.use('/api/sales', require('./modules/sales/sales.routes'));
    app.use('/api/stores', require('./modules/stores/store.routes'));
    app.use('/api/warehouses', require('./modules/warehouses/warehouse.routes'));
    app.use('/api/suppliers', require('./modules/suppliers/supplier.routes'));
    app.use('/api/delivery-challans', require('./modules/deliveryChallan/deliveryChallan.routes'));
    app.use('/api/delivery-challan', require('./modules/dispatch/dispatch.routes'));
    app.use('/api/purchase', require('./modules/purchase/purchase.routes'));
    app.use('/api/purchase-orders', require('./modules/purchase/purchaseOrder.routes'));
    app.use('/api/reports', require('./modules/reports/report.routes'));
    app.use('/api/grn', require('./modules/grn/grn.routes'));
    app.use('/api/brands', require('./modules/brands/brand.routes'));
    app.use('/api/customers', require('./modules/customers/customer.routes'));
    app.use('/api/dispatch', require('./modules/dispatch/dispatch.routes'));
    app.use('/api/dashboard', require('./modules/dashboard/dashboard.routes'));
    app.use('/api/stock-returns', require('./modules/stockReturn/stockReturn.routes'));
    app.use('/api/pricing', require('./modules/pricing/pricing.routes'));
    app.use('/api/settings', require('./modules/settings/settings.routes'));
    app.use('/api/barcodes', require('./modules/barcodes/barcode.routes'));
    app.use('/api/returns', require('./modules/sales/salesReturn.routes'));
    app.use('/api/production', require('./modules/production/production.routes'));
};

module.exports = registerRoutes;
