export const salesData = [
  {
    id: 'sal-1',
    invoiceNumber: 'INV-24001',
    date: '2026-02-26',
    warehouseId: 'wh-1',
    customerId: 'cus-1',
    customerName: 'Neel Fashion Point',
    customerMobile: '9898011122',
    salesmanId: 'sl-1',
    salesmanName: 'Vikram Mehta',
    items: [
      {
        variantId: 'var-4',
        itemName: 'Essential Cotton Tee',
        styleCode: 'STY-CTN-TEE',
        size: 'S',
        color: 'White',
        sku: 'STY-CTN-TEE-S-WHITE',
        quantity: 3,
        rate: 499,
        discount: 5,
        tax: 5,
        amount: 1492.11,
      },
      {
        variantId: 'var-1',
        itemName: 'Classic Denim Jacket',
        styleCode: 'STY-DNM-JKT',
        size: 'M',
        color: 'Blue',
        sku: 'STY-DNM-JKT-M-BLUE',
        quantity: 1,
        rate: 1899,
        discount: 0,
        tax: 12,
        amount: 2126.88,
      },
    ],
    totals: {
      totalItems: 2,
      totalQuantity: 4,
      grossAmount: 3396,
      lineDiscount: 74.85,
      billDiscount: 0,
      taxAmount: 297.96,
      loyaltyRedeemed: 0,
      netPayable: 3619.11,
    },
    payment: {
      mode: 'UPI',
      split: null,
      amountPaid: 3619.11,
      changeReturned: 0,
      dueAmount: 0,
      status: 'Paid',
    },
    status: 'Completed',
  },
  {
    id: 'sal-2',
    invoiceNumber: 'INV-24002',
    date: '2026-02-27',
    warehouseId: 'wh-2',
    customerId: null,
    customerName: 'Walk-in Customer',
    customerMobile: '',
    salesmanId: 'sl-2',
    salesmanName: 'Prakash Rao',
    items: [
      {
        variantId: 'var-5',
        itemName: 'Essential Cotton Tee',
        styleCode: 'STY-CTN-TEE',
        size: 'M',
        color: 'Black',
        sku: 'STY-CTN-TEE-M-BLACK',
        quantity: 2,
        rate: 549,
        discount: 0,
        tax: 5,
        amount: 1152.9,
      },
    ],
    totals: {
      totalItems: 1,
      totalQuantity: 2,
      grossAmount: 1098,
      lineDiscount: 0,
      billDiscount: 20,
      taxAmount: 53.9,
      loyaltyRedeemed: 0,
      netPayable: 1131.9,
    },
    payment: {
      mode: 'Cash',
      split: null,
      amountPaid: 1200,
      changeReturned: 68.1,
      dueAmount: 0,
      status: 'Paid',
    },
    status: 'Completed',
  },
];

export const salesReturnsData = [
  {
    id: 'sret-1',
    returnNumber: 'SRET-8001',
    saleId: 'sal-1',
    date: '2026-02-28',
    reason: 'Size mismatch',
    customerId: 'cus-1',
    customerName: 'Neel Fashion Point',
    warehouseId: 'wh-1',
    items: [
      {
        variantId: 'var-4',
        itemName: 'Essential Cotton Tee',
        size: 'S',
        color: 'White',
        sku: 'STY-CTN-TEE-S-WHITE',
        soldQty: 3,
        returnQty: 1,
        rate: 499,
        amount: 499,
      },
    ],
    totals: {
      totalQuantity: 1,
      refundAmount: 499,
    },
  },
];
