export const saleOrdersData = [
  {
    id: 'so-1',
    orderNumber: 'SO-001',
    date: '2026-02-25',
    customerId: 'cus-1',
    customerName: 'Neel Fashion Point',
    priceListId: 'pl-1',
    salesmanId: 'sl-1',
    items: [
      {
        variantId: 'var-4',
        itemName: 'Essential Cotton Tee',
        styleCode: 'STY-CTN-TEE',
        size: 'S',
        color: 'White',
        sku: 'STY-CTN-TEE-S-WHITE',
        quantity: 10,
        rate: 449,
        discount: 5,
        tax: 5,
        amount: 4485.38,
      },
      {
        variantId: 'var-1',
        itemName: 'Classic Denim Jacket',
        styleCode: 'STY-DNM-JKT',
        size: 'M',
        color: 'Blue',
        sku: 'STY-DNM-JKT-M-BLUE',
        quantity: 5,
        rate: 1799,
        discount: 0,
        tax: 12,
        amount: 10074.4,
      },
    ],
    totals: { totalQuantity: 15, grossAmount: 14985, lineDiscount: 749.25, taxAmount: 1405.45, netAmount: 15641.2 },
    status: 'Packed',
  },
];

export const packingSlipsData = [
  {
    id: 'ps-1',
    slipNumber: 'PS-001',
    saleOrderId: 'so-1',
    warehouseId: 'wh-1',
    date: '2026-02-26',
    items: [
      { variantId: 'var-4', stockId: 'stk-5', sku: 'STY-CTN-TEE-S-WHITE', qty: 10, boxNumber: 'B1' },
      { variantId: 'var-1', stockId: 'stk-1', sku: 'STY-DNM-JKT-M-BLUE', qty: 5, boxNumber: 'B2' },
    ],
    status: 'Completed',
  },
];

export const deliveryOrdersData = [
  {
    id: 'do-1',
    doNumber: 'DO-001',
    saleOrderId: 'so-1',
    packingSlipId: 'ps-1',
    customerId: 'cus-1',
    customerName: 'Neel Fashion Point',
    warehouseId: 'wh-1',
    date: '2026-02-27',
    remarks: '',
    items: [
      {
        variantId: 'var-4',
        itemName: 'Essential Cotton Tee',
        styleCode: 'STY-CTN-TEE',
        size: 'S',
        color: 'White',
        sku: 'STY-CTN-TEE-S-WHITE',
        quantity: 10,
        rate: 449,
        discount: 5,
        tax: 5,
      },
      {
        variantId: 'var-1',
        itemName: 'Classic Denim Jacket',
        styleCode: 'STY-DNM-JKT',
        size: 'M',
        color: 'Blue',
        sku: 'STY-DNM-JKT-M-BLUE',
        quantity: 5,
        rate: 1799,
        discount: 0,
        tax: 12,
      },
    ],
    totals: { totalQuantity: 15, grossAmount: 14985, lineDiscount: 749.25, taxAmount: 1405.45, netAmount: 15641.2 },
    status: 'Pending',
  },
];
