export const purchasesData = [
  {
    id: 'pur-1',
    supplierId: 'sup-1',
    billNumber: 'BILL-1001',
    billDate: '2026-02-18',
    warehouseId: 'wh-1',
    purchaseType: 'Local',
    remarks: 'Season opening stock',
    items: [
      {
        variantId: 'var-1',
        lotNumber: 'LOT-001',
        itemName: 'Classic Denim Jacket',
        styleCode: 'STY-DNM-JKT',
        size: 'M',
        color: 'Blue',
        sku: 'STY-DNM-JKT-M-BLUE',
        brand: 'North Trail Denim',
        category: 'Denim Jackets',
        quantity: 20,
        rate: 1250,
        discount: 5,
        tax: 12,
        amount: 26600,
        status: 'Active',
      },
      {
        variantId: 'var-4',
        lotNumber: 'LOT-002',
        itemName: 'Essential Cotton Tee',
        styleCode: 'STY-CTN-TEE',
        size: 'S',
        color: 'White',
        sku: 'STY-CTN-TEE-S-WHITE',
        brand: 'Zeto Originals',
        category: 'Menswear',
        quantity: 50,
        rate: 250,
        discount: 0,
        tax: 5,
        amount: 13125,
        status: 'Active',
      },
    ],
    totals: {
      totalQuantity: 70,
      grossAmount: 37500,
      totalDiscount: 1250,
      totalTax: 3475,
      otherCharges: 0,
      netAmount: 39725,
    },
    status: 'Partially Returned',
  },
  {
    id: 'pur-2',
    supplierId: 'sup-2',
    billNumber: 'BILL-1002',
    billDate: '2026-02-25',
    warehouseId: 'wh-2',
    purchaseType: 'Inter-State',
    remarks: '',
    items: [
      {
        variantId: 'var-2',
        lotNumber: 'LOT-003',
        itemName: 'Classic Denim Jacket',
        styleCode: 'STY-DNM-JKT',
        size: 'L',
        color: 'Blue',
        sku: 'STY-DNM-JKT-L-BLUE',
        brand: 'North Trail Denim',
        category: 'Denim Jackets',
        quantity: 15,
        rate: 1280,
        discount: 2,
        tax: 12,
        amount: 21073.92,
        status: 'Active',
      },
    ],
    totals: {
      totalQuantity: 15,
      grossAmount: 19200,
      totalDiscount: 384,
      totalTax: 2257.92,
      otherCharges: 0,
      netAmount: 21073.92,
    },
    status: 'Received',
  },
];

export const purchaseReturnsData = [
  {
    id: 'pret-1',
    returnNumber: 'RET-9001',
    purchaseId: 'pur-1',
    supplierId: 'sup-1',
    warehouseId: 'wh-1',
    date: '2026-02-22',
    remarks: 'Damaged on opening',
    items: [
      {
        variantId: 'var-1',
        lotNumber: 'LOT-001',
        itemName: 'Classic Denim Jacket',
        size: 'M',
        color: 'Blue',
        sku: 'STY-DNM-JKT-M-BLUE',
        purchasedQty: 20,
        returnQty: 2,
        rate: 1250,
        amount: 2500,
      },
      {
        variantId: 'var-4',
        lotNumber: 'LOT-002',
        itemName: 'Essential Cotton Tee',
        size: 'S',
        color: 'White',
        sku: 'STY-CTN-TEE-S-WHITE',
        purchasedQty: 50,
        returnQty: 5,
        rate: 250,
        amount: 1250,
      },
    ],
    totals: {
      totalQuantity: 7,
      totalAmount: 3750,
    },
  },
];
