export const warehousesData = [
  { id: 'wh-1', name: 'Central Warehouse', code: 'WH-CEN-01' },
  { id: 'wh-2', name: 'North Branch Depot', code: 'WH-NOR-02' },
  { id: 'wh-3', name: 'South Transit Hub', code: 'WH-SOU-03' },
];

const DEFAULT_LOT = '';

export const stockData = [
  {
    id: 'stk-1',
    variantId: 'var-1',
    lotNumber: DEFAULT_LOT,
    itemName: 'Classic Denim Jacket',
    styleCode: 'STY-DNM-JKT',
    brand: 'North Trail Denim',
    category: 'Denim Jackets',
    size: 'M',
    color: 'Blue',
    sku: 'STY-DNM-JKT-M-BLUE',
    warehouseId: 'wh-1',
    quantity: 42,
    reserved: 5,
    status: 'Active',
  },
  {
    id: 'stk-2',
    variantId: 'var-1',
    lotNumber: DEFAULT_LOT,
    itemName: 'Classic Denim Jacket',
    styleCode: 'STY-DNM-JKT',
    brand: 'North Trail Denim',
    category: 'Denim Jackets',
    size: 'M',
    color: 'Blue',
    sku: 'STY-DNM-JKT-M-BLUE',
    warehouseId: 'wh-2',
    quantity: 16,
    reserved: 2,
    status: 'Active',
  },
  {
    id: 'stk-3',
    variantId: 'var-2',
    lotNumber: DEFAULT_LOT,
    itemName: 'Classic Denim Jacket',
    styleCode: 'STY-DNM-JKT',
    brand: 'North Trail Denim',
    category: 'Denim Jackets',
    size: 'L',
    color: 'Blue',
    sku: 'STY-DNM-JKT-L-BLUE',
    warehouseId: 'wh-1',
    quantity: 36,
    reserved: 4,
    status: 'Active',
  },
  {
    id: 'stk-4',
    variantId: 'var-3',
    lotNumber: DEFAULT_LOT,
    itemName: 'Classic Denim Jacket',
    styleCode: 'STY-DNM-JKT',
    brand: 'North Trail Denim',
    category: 'Denim Jackets',
    size: 'XL',
    color: 'Black',
    sku: 'STY-DNM-JKT-XL-BLACK',
    warehouseId: 'wh-1',
    quantity: 18,
    reserved: 1,
    status: 'Inactive',
  },
  {
    id: 'stk-5',
    variantId: 'var-4',
    lotNumber: DEFAULT_LOT,
    itemName: 'Essential Cotton Tee',
    styleCode: 'STY-CTN-TEE',
    brand: 'Zeto Originals',
    category: 'Menswear',
    size: 'S',
    color: 'White',
    sku: 'STY-CTN-TEE-S-WHITE',
    warehouseId: 'wh-1',
    quantity: 120,
    reserved: 20,
    status: 'Active',
  },
  {
    id: 'stk-6',
    variantId: 'var-4',
    lotNumber: DEFAULT_LOT,
    itemName: 'Essential Cotton Tee',
    styleCode: 'STY-CTN-TEE',
    brand: 'Zeto Originals',
    category: 'Menswear',
    size: 'S',
    color: 'White',
    sku: 'STY-CTN-TEE-S-WHITE',
    warehouseId: 'wh-2',
    quantity: 40,
    reserved: 6,
    status: 'Active',
  },
  {
    id: 'stk-7',
    variantId: 'var-5',
    lotNumber: DEFAULT_LOT,
    itemName: 'Essential Cotton Tee',
    styleCode: 'STY-CTN-TEE',
    brand: 'Zeto Originals',
    category: 'Menswear',
    size: 'M',
    color: 'Black',
    sku: 'STY-CTN-TEE-M-BLACK',
    warehouseId: 'wh-1',
    quantity: 98,
    reserved: 10,
    status: 'Active',
  },
  {
    id: 'stk-8',
    variantId: 'var-5',
    lotNumber: DEFAULT_LOT,
    itemName: 'Essential Cotton Tee',
    styleCode: 'STY-CTN-TEE',
    brand: 'Zeto Originals',
    category: 'Menswear',
    size: 'M',
    color: 'Black',
    sku: 'STY-CTN-TEE-M-BLACK',
    warehouseId: 'wh-3',
    quantity: 12,
    reserved: 2,
    status: 'Active',
  },
];

export const movementData = [
  {
    id: 'mov-1',
    date: '2026-02-20',
    variantId: 'var-1',
    sku: 'STY-DNM-JKT-M-BLUE',
    itemName: 'Classic Denim Jacket',
    styleCode: 'STY-DNM-JKT',
    size: 'M',
    color: 'Blue',
    warehouseId: 'wh-1',
    type: 'Purchase',
    quantityChange: 42,
    reference: 'PO-1021',
    user: 'Admin',
  },
  {
    id: 'mov-2',
    date: '2026-02-22',
    variantId: 'var-4',
    sku: 'STY-CTN-TEE-S-WHITE',
    itemName: 'Essential Cotton Tee',
    styleCode: 'STY-CTN-TEE',
    size: 'S',
    color: 'White',
    warehouseId: 'wh-1',
    type: 'Sale',
    quantityChange: -8,
    reference: 'SO-5531',
    user: 'Admin',
  },
  {
    id: 'mov-3',
    date: '2026-02-24',
    variantId: 'var-5',
    sku: 'STY-CTN-TEE-M-BLACK',
    itemName: 'Essential Cotton Tee',
    styleCode: 'STY-CTN-TEE',
    size: 'M',
    color: 'Black',
    warehouseId: 'wh-3',
    type: 'Transfer',
    quantityChange: 12,
    reference: 'TRN-301',
    user: 'Admin',
  },
];
